### ISSUE TITLE
Support loading leader runs into browser on demand

### ISSUE THREAD

**Issue by janeeisenstein** [simplworld/simpl#2]
Currently, Simpl loads data from all active runs in which a user is a leader into the browser. This causes performance problems for larger simulations where leaders are associated with lots of runs with lots of data.

This ticket covers updating `simpl-react` and `simpl-modelservice` to support games that:
- provide leaders with information at login about their runs without loading all run data into the browser's simpl redux store.
- allow leaders to select one run to load into the browser's simpl redux store at a time
- unload the currently loaded run from the browser's simpl redux store

Although this enhancement focuses on loading leader run data on demand, providing these features may lay  groundwork for allowing users to be players in more than one active run.

Subissues:

- simplworld/simpl-react#28
- simplworld/simpl-modelservice#33

**Comment by fcurella** [comment]
Another low-hanging fruit to consider is that currently, the redux store in simpl-react is made of arrays. That means that every time we need a specific object, we need to iterate over arrays.

Converting the store's data structure from arrays to objects will allow for faster data selection. But it will be a backward-incompatible change for simulations that manipulate the store directory (ie: that don't use the utilities in https://github.com/simplworld/simpl-react/blob/master/src/utils/collections.js).

To be clear, I'm not arguing against the proposed changes. The redux-store refactor would be complementary. But I think it's a smaller task that could improve performances for much less work, and maybe that's what we should start with.

**Comment by janeeisenstein** [comment]
@fcurella Just loading the data for multiple runs into the browser can been overwhelming. I am also looking to make non-breaking changes and our simulation js code 'knows' simpl data is stored as arrays. It sounds like all current simulation simpl data selection/filtering would need to be rewritten to work with what you're suggesting. Is that correct?

**Comment by fcurella** [comment]
> However, no simulation I've been involved with modifies the simpl store directly. Is that what you meant by 'manipulate the store directory'?

Correct. If all simulations use the functions `utils/collections.js`, then we can use those functions as an abstraction layer. We could change how they access the data in the store, and the sims would just keep working.

As you point out, this would not solve 'transport' issue (ie: moving lots of data from api -> modelservice -> browser).

As for memory footprint issues, I would be surprised if a sim has so much data that just keeping it in RAM causes issues with the browser. But I think it could be possible the _process_ of storing it (ie: adding it to the store) could be heavy. Definitely something that needs to be investigated with the memory profiler.

**Comment by janeeisenstein** [comment]
@fcurella A single completed scenario of our Pivot or Perish game has over 10,000 result values. Each period's result values are stored as json data on a single result. I added the simpl decorator `loadWorldResults` parameter just to prevent this data from being loaded into the simpl store.

**Comment by janeeisenstein** [comment]
Implemented in simpl-modelservice v0.9.1 and simpl-react v0.8.0.
